# Generated by Django 6.0 on 2025-12-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_no", models.CharField(max_length=10, unique=True)),
                ("floor_no", models.IntegerField()),
                ("no_beds", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
