# Generated by Django 6.0 on 2025-12-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="id",
        ),
        migrations.AlterField(
            model_name="room",
            name="room_no",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
