# Generated by Django 6.0 on 2025-12-25 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Rooms", "0002_remove_room_id_alter_room_room_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone_no", models.CharField(max_length=15)),
                ("adhar_no", models.CharField(max_length=12, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "room_no",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Rooms.room",
                    ),
                ),
            ],
        ),
    ]
