# Generated by Django 5.2.4 on 2025-12-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="adhar_no",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
