# Generated by Django 6.0 on 2026-02-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Persons", "0002_alter_person_adhar_no_alter_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
